name: Deploy Votes InReady V1

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Masuk folder project
            cd ${{ secrets.PATH_VPS }}

            # 2. Ambil alih ownership sementara (agar bisa git, npm, composer)
            sudo chown -R $USER:$USER .

            # 3. Update kodingan
            git fetch --all
            git reset --hard origin/main

            # 4. Install & build frontend (Vite + Tailwind)
            /usr/bin/npm install
            /usr/bin/npm run build

            # 5. Install dependency PHP
            /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # 6. Laravel commands
            /usr/bin/php artisan migrate --force
            /usr/bin/php artisan storage:link
            /usr/bin/php artisan optimize:clear
            /usr/bin/php artisan config:cache
            /usr/bin/php artisan route:cache
            /usr/bin/php artisan view:cache

            # 7. Kembalikan ownership ke www (wajib — agar Nginx/PHP-FPM bisa serve)
            sudo chown -R www:www .
            sudo chmod -R 775 storage bootstrap/cache

            echo "Deployment Berhasil!"